apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  replicas: 1
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products
        image: namitamaan/products
 
---
apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  type: NodePort
  selector:
    app: products
  ports:
  - port: 80
    targetPort: 8082
    nodePort: 32500
